from typing import Final

FREE_SPACE: Final = "FREE SPACE"

QUESTIONS: Final[list[str]] = [
    "uses Vim motions in an editor that is not Vim",
    "has at least 15 browser tabs open for debugging",
    "renames variables three times before committing",
    "has a favorite keyboard shortcut they evangelize",
    "has said 'it works on my machine' this month",
    "customized their IDE theme beyond recognition",
    "writes TODOs and actually comes back to them",
    "has strong opinions about tabs vs spaces",
    "has fixed a bug by adding a print statement first",
    "has copy-pasted a stack trace into search today",
    "uses dark mode in every developer tool",
    "has an alias in their shell they are proud of",
    "has accidentally force-closed the wrong terminal",
    "names branches better than commit messages",
    "has a side project that is mostly README",
    "can explain rubber duck debugging with a straight face",
    "has merged right before a meeting and hoped for the best",
    "keeps one ancient snippet around for good luck",
    "has a meme folder just for developer reactions",
    "has debated semicolons in at least one code review",
    "has switched IDEs and switched back within a week",
    "can spot AI-generated code by the variable names",
    "has watched CI fail for a reason they already knew",
    "has used a breakpoint where a test should have been",
    "has one package manager they defend passionately",
    "has reopened a ticket they marked as done",
    "has learned a framework from one chaotic tutorial thread",
    "has asked 'quick question' and posted a full architecture diagram",
    "has celebrated deleting more code than they wrote",
]
